HW2
Midwayx/2020-2-Atom-QA-Python-D-Presnyakov pull request #2
Opened 2020-10-12 22:33 UTC by Midwayx

# Домашнее задание №2

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
Написаны автотесты в соответствии с заданием.
 дефолтные login/password можно заменить используя 
--user "email@example.ru" и --password --"password"

P.S. Надеюсь, что не будете плеваться и кидаться камнями, но 1 тест в паралельном режиме иногда падает.

2020-10-18 19:33 UTC, Midwayx commented
Что-то я накосячил с гитом, забыл обновить мастер локальный =\

2020-10-26 13:53 UTC, snicks92 requested changes
Все в целом хорошо, но есть вопросы по тестам, в особенности по конструкциям try except TimeoutException

2020-10-26 13:53 UTC, snicks92 commented on hw2/code/tests/test_my_target.py
> +            assert False
То есть если сработает таймаут, то тест пройдет? А если таки залогинит?)

2020-10-26 13:53 UTC, snicks92 commented on hw2/code/tests/test_my_target.py
> +            assert False
не совсем понятна эта конструкция. если созданный сегмент не будет найдет то и так будет ошибка. только более понятная - таймаут при поиске, а не assert False

2020-10-26 13:53 UTC, snicks92 commented on hw2/code/tests/test_my_target.py
> +            assert False
не уверен что это нужно тут, учитывая что есть отдельный тест на создание сегмента

2020-10-26 13:53 UTC, snicks92 commented on hw2/code/tests/test_my_target.py
> +        self.segment_page.find(self.segment_page.locator.NAME_LOCATOR(name))
тут явно нужно проверять что сегмента больше нет, то есть ждать пока он пропадет. иначе удаление происходит так быстро что поиск отрабатывает и тест проходит ничего не проверяя

2020-10-26 17:56 UTC, Midwayx commented
Поправил замечания, слегка улучшил код.

2020-10-26 17:58 UTC, Midwayx commented
P.S. -30% очень жестоко получается за несколько бессонных ночей :)
P.P.S Нигде ведь не указано, что время Московское, а не местное?)

2020-10-26 22:16 UTC, snicks92 commented
> P.P.S Нигде ведь не указано, что время Московское, а не местное?)

Ну на сайте вообще до 18:00 =)

2020-10-26 22:18 UTC, snicks92 approved these changes

2020-10-26 22:19 UTC, merged

2020-10-26 22:19 UTC, snicks92 commented
Теперь ок. Давай округлим до 9, и чтобы по честному и чтобы тебе не было обидно

2020-10-26 22:21 UTC, Midwayx commented
Справедливо, спасибо